module ADLicenseLint
  module Constant
    MARKDOWN_FORMAT_OPTION = "md"
    TERMINAL_FORMAT_OPTION = "term"
    AVAILABLE_OPTIONS = [MARKDOWN_FORMAT_OPTION, TERMINAL_FORMAT_OPTION]
    ACCEPTED_LICENSES = ["MIT", "Apache", "BSD"]
  end
end
